name: countries_utils_example
description: A pure Dart CLI demo for the countries_utils package.

publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  countries_utils:
    path: ../
