include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - cancel_subscriptions
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_lambdas
    - use_string_buffers
